// data-buying.js — Buying pillar card definitions
// Source: Confluence LLTT Work Management Dashboard (APREC space)
// Live Jira: https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard
// Depends on: data.js (own, res, TBD_OWNERS, pptOwners)

const CARDS_BUYING = [
  {
    id: 'neo-replatform', title: 'AEX Replatform \u2014 Neo', icon: '\uD83C\uDFC6',
    status: 'completed', statusLabel: 'Completed', quarter: 'completed',
    targetDate: 'Mar 2, 2026', tag: 'Major Win',
    description: 'All AEX Fashion departments migrated to the Neo platform (D23, D25, D34 final). Re-architected backend integration layer — 700+ automated test cases, 360+ issues resolved. Now in Hypercare.',
    businessBenefit: '50% reduction in support tickets YoY. 1\u20132 day deployment cycles (down from 4\u20135 days). Foundation for all future AEX capability delivery.',
    techIntegration: 'Replaced legacy integration layer with modern resilient architecture. Automation via MCP Playwright with 99% automatable E2E test cases. Q1 prioritized backlog: 6 Fast Follows, 15 Stability, 3 Transformation items.',
    successMetrics: 'Support ticket volume down 50% YoY. Deployment cycle 1\u20132 days. Zero data-loss incidents on platform transition.',
    owners: pptOwners('Brett Reid', '', 'Michael Allen'), resources: res(),
  },
  {
    id: 'aex-stability', title: 'AEX Stability & Quality of Life', icon: '\uD83D\uDEE1\uFE0F',
    status: 'yellow', statusLabel: 'Yellow \u2014 At Risk',
    quarter: 'Q1', targetDate: 'April 30, 2026', tag: 'Critical Program',
    description: '24 AEX Stabilization OPIFs prioritized by business. 19 committed for Q1 & Q2 delivery. 5 pending commitment (3 in product discovery, 2 pending sizing). Of 24: 18 Green, 5 Yellow, 1 Red. Key MTAP tickets in WIP: MTAP-9154, MTAP-7474, MTAP-7438, MTAP-6808, MTAP-9541, MTAP-9570, MTAP-9543.',
    businessBenefit: 'Merchants gain confidence that AEX decisions execute correctly — reducing costly mistakes from accidental deletions, incorrect size ordering, and data inconsistencies.',
    techIntegration: 'Key at-risk items tracked in Jira: Automated Item Setup discovery (OPIF-344926), Handle Leftover Space (OPIF-293460), Tagging & Affinity Graph (OPIF-325602). Active bug fixes tracked as PRB incidents in MTAP project.',
    pathToGreen: '5 OPIFs pending commitment: product and business teams accelerating discovery phase. Weekly OPIF status reviewed in Planning Dashboard. Target: all 19 committed OPIFs delivered by Q1/Q2 BTL dates.',
    successMetrics: 'All 24 OPIFs resolved or committed. Merchant satisfaction score improves. Support ticket volume continues downward trend from Neo baseline.',
    owners: pptOwners('Brett Reid', 'Prasanth Chalikandi', 'Michael Allen'),
    resources: res('https://jira.walmart.com/browse/OPIF-344926'),
  },
  {
    id: 'longterm-buying', title: 'Long Leadtime Buying Workflow (LLTT)', icon: '\uD83D\uDDD3\uFE0F',
    status: 'green', statusLabel: 'Green \u2014 In Progress',
    quarter: 'Q1', targetDate: 'Feb\u2013Apr 2026',
    description: 'Streamlined long leadtime buying workflow (LLTT program) covering the full Setup phase through AEX — integrating AP Tool as line plan into AEX flow, enabling suppliers to communicate item details directly into the tool, and connecting ecosystem tools to eliminate duplicative email communication. Sourcing and rack planning visualization tools make decisions easier. Builds foundations of tagging and fixture library. Jira tracked via labels: LLTT and LLTTO.',
    businessBenefit: 'Buyers and planners work in one shared environment for long leadtime decisions — eliminating spreadsheet and email-based coordination. Goals: 90% of buys on happy path, zero rekeys, reduced merchant hours.',
    techIntegration: 'LLTT initiative tracked in OPIF Jira project under initiative: U.S. Omni Tech: MerchTools: Assortment Excellence: Fashion Apparel [15922203]. Labels: LLTT / LLTTO. View all active OPIFs via the Confluence dashboard.',
    successMetrics: 'Long leadtime buy decisions finalized in AEX across all supported departments by seasonal deadline. Reduction in off-system spreadsheet workarounds. 90% of buys on confirmed happy path.',
    owners: TBD_OWNERS(),
    resources: res('https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard'),
  },
  {
    id: 'auto-item-setup', title: 'Automated Item Setup', icon: '\u2699\uFE0F',
    status: 'green', statusLabel: 'Green \u2014 On Track',
    quarter: 'Q2', targetDate: 'April 30, 2026', tag: 'Critical Program',
    description: '3 pillars all on track: (1) Gen AI Data Enrichment, (2) Parent Anchored Variant Groups, (3) Seamless Data Flow (AEX \u2192 Item). Outcome: eliminate merchant manual item reconstruction and oversight.',
    businessBenefit: 'Removes manual item setup work from Fashion Merchants entirely. Estimated to save hundreds of hours per season across the merchant organization.',
    techIntegration: 'AEX captures assortment intent and triggers automated item setup via integration with ISAM, Supplier One, and item setup systems. IDC handles exceptions through a managed queue.',
    successMetrics: 'Automated item setup rate >90% of eligible items. Merchant time on manual item setup reduced to near zero. PO creation cycle time reduced from days to hours.',
    owners: pptOwners('Michael Allen', '', ''), resources: res(),
  },
  {
    id: 'fashion-fixture-allocation-buying', title: 'Fashion Fixture Allocation (Visual)', icon: '\uD83C\uDFEA',
    status: 'green', statusLabel: 'Green \u2014 In Discovery',
    quarter: 'Q2', targetDate: 'Jul 31, 2026',
    description: 'Easy, visual fixture allocation capability enabling merchants to plan product placement across store fixtures with an intuitive visual interface — in discovery for S2 delivery.',
    businessBenefit: 'Merchants can visualize and optimize fixture allocation without complex spreadsheets, leading to better product placement decisions and fewer fixture conflicts.',
    techIntegration: 'Built within the buying workflow toolset. Integrates with AEX assortment data for product-to-fixture mapping and with store planogram systems.',
    successMetrics: 'Visual fixture allocation adopted across target departments. Fixture conflicts reduced. Merchant fixture planning time measurably reduced.',
    owners: pptOwners('Brett Reid', '', 'Michael Allen'), resources: res(),
  },
  {
    id: 'ai-item-repository', title: 'AI Item Repository Launch', icon: '\uD83E\uDDE0',
    status: 'green', statusLabel: 'Green \u2014 In Discovery',
    quarter: 'Q2', targetDate: 'Jul 31, 2026',
    description: 'AI-powered item repository providing merchants with intelligent product reuse recommendations — surfacing relevant historical items to accelerate new product development.',
    businessBenefit: 'Reduces time spent creating near-duplicate items from scratch. AI surfaces the closest existing items, enabling merchants to reuse, modify, or replace rather than rebuild.',
    techIntegration: 'AI repository indexes AEX item history and product attributes. ML model provides similarity scoring. Surfaced in AEX line plan and item creation workflows.',
    successMetrics: 'AI item reuse rate tracked and improving. New item creation time reduced for target merchant groups. Duplicate item rate decreasing quarter over quarter.',
    owners: pptOwners('Brett Reid', '', 'Michael Allen'), resources: res(),
  },
  {
    id: 'size-pack-bq', title: 'Automated Size/Pack Buy Quantification', icon: '\uD83D\uDCE6',
    status: 'green', statusLabel: 'Green \u2014 Discovery Done',
    quarter: 'Q2', targetDate: 'Jul 31, 2026',
    description: 'Automation of size and pack buy quantification (BQ) calculations — eliminating the manual sizing step currently owned by merchants. Moves size logic into BQ module (calc changes in Flow Plan, removal of manual Size Profile screen in Size & Pack). Configurable minimum initial set qty for core sizes. Pre-generated DS results for all 3 Like Finelines recommended by AEX.',
    businessBenefit: 'Removes the most time-consuming manual calculation in the buying process. Size curves derived from data rather than merchant memory, reducing size-related markdowns.',
    techIntegration: 'Jira: OPIF-325374 (Size/Pack automation). Size/Pack BQ engine integrates with AEX demand signal, historical sell-through by size, and BPE for seasonal demand curve inputs. Discovery completed.',
    successMetrics: 'Automated size/pack BQ in use across target departments by Jul 31. Manual sizing calculation time reduced to near zero. Size-based markdown rate decreasing.',
    owners: pptOwners('Brett Reid', '', 'Michael Allen'),
    resources: res('https://jira.walmart.com/browse/OPIF-325374'),
  },
  {
    id: 'ap-tool-lineplan', title: 'AP Tool Line Plan Integration w/ AEX', icon: '\uD83D\uDCC8',
    status: 'green', statusLabel: 'Green \u2014 In Discovery',
    quarter: 'Q3', targetDate: 'Oct 30, 2026',
    description: 'Integration of AP Tool (Assortment Planning) line plan with AEX, enabling assortment decisions from line planning to flow directly into buying execution without manual re-entry. Enables fashion merchants to use Assortment Planning\u2019s Plan Creation & Plan List as the Fashion Line Plan system of record (replaces AEX legacy LP module).',
    businessBenefit: 'Eliminates the gap between line planning (AP Tool) and buying execution (AEX). Merchants no longer re-enter line plan decisions into AEX manually.',
    techIntegration: 'Jira: OPIF-325568 (AEX Fashion LP Replacement), OPIF-325569 (Shared Item Repository connection). AP Tool line plan data syncs to AEX via shared integration layer. Fashion Excel Upload enabled via existing Assortment Planning capability.',
    successMetrics: 'AP Tool and AEX sharing live line plan data by Oct 30. Zero manual exports from AP Tool to AEX for in-scope workflows. Fashion metrics and attributes fully enabled.',
    owners: pptOwners('Brett Reid', '', 'Michael Allen'),
    resources: res('https://jira.walmart.com/browse/OPIF-325568'),
  },
  {
    id: 'bam-collab-intent', title: 'BAM / Collab Intent Integration', icon: '\uD83E\uDD1D',
    status: 'green', statusLabel: 'Green \u2014 On Track',
    quarter: 'Q3', targetDate: 'Oct 30, 2026',
    description: 'Integration of BAM (Buying Assortment Management) and Collab Intent data into the buying workflow, enabling collaborative assortment signals to inform buying decisions in AEX.',
    businessBenefit: 'Buying decisions reflect collaborative intent data automatically — reducing the lag between collaboration signals and committed buy decisions.',
    techIntegration: 'BAM and Collab Intent signals integrated into AEX via the shared event layer. Assortment recommendations automatically weighted by collaborative intent scores.',
    successMetrics: 'BAM/Collab Intent data live in AEX buying workflow. Adoption confirmed across target buying teams by Oct 30.',
    owners: pptOwners('Brett Reid', '', 'Michael Allen'), resources: res(),
  },
  {
    id: 'oneitem-expanded-sources', title: 'OneItem: Expanded Sources (ROM, 3P, Circana)', icon: '\uD83C\uDF10',
    status: 'green', statusLabel: 'Green \u2014 On Track',
    quarter: 'Q4', targetDate: 'Jan 30, 2027',
    description: 'Expansion of OneItem to include additional data sources: ROM (Range of Motion), 3rd-party data, and Circana — providing richer product intelligence for buying and assortment decisions.',
    businessBenefit: 'Merchants access a broader, richer set of market and performance signals in one place — improving buying decisions with external market context alongside internal data.',
    techIntegration: 'OneItem data pipeline expanded to ingest ROM, 3P market data feeds, and Circana retail data. Surfaced in AEX item records and assortment planning views.',
    successMetrics: 'ROM, 3P, and Circana sources live in OneItem. Merchant adoption of expanded data sources confirmed. Assortment decision quality (measured by sell-through) trending up.',
    owners: pptOwners('Brett Reid', '', 'Michael Allen'), resources: res(),
  },
  {
    id: 'bq-enterprise-service', title: 'Buy Quantification as Enterprise Service', icon: '\uD83D\uDCCA',
    status: 'roadmap', statusLabel: 'Roadmap \u2014 Recommend & Optimize Phase',
    quarter: 'Q3', targetDate: 'Aug\u2013Oct 2026',
    description: 'Buy Quantification and Flow delivered as a shared enterprise service — providing demand-driven buy quantity recommendations across all Fashion workstreams without each team running independent BQ calculations. Part of the Recommend & Optimize phase of the LLTT roadmap (Q3 FY27 – Q1 FY28). Includes rollup reporting and dynamic PO re-distribution capabilities.',
    businessBenefit: 'Single authoritative buy quantity signal across all Fashion buying teams. Replaces manual BQ spreadsheets and per-department workarounds. Enables dynamic redistribution of POs as in-season signals emerge.',
    techIntegration: 'Jira: OPIF-344926. BQ enterprise service builds on the DS National Forecasting microservice and automated size/pack work. Outputs consumed by AEX (commit), DBP (wave planning), and supply chain for automated PO creation. Includes rules-based Flow Plan automation.',
    successMetrics: 'BQ enterprise service adopted across all target Fashion buying departments. Manual BQ calculation workarounds eliminated. Dynamic PO re-distribution live and operational for in-season adjustments.',
    owners: pptOwners('Brett Reid', 'TBD', 'Michael Allen'),
    resources: res('https://jira.walmart.com/browse/OPIF-344926'),
  },
  {
    id: 'commitment-report-redesign', title: 'Commitment Report Redesign', icon: '\uD83D\uDCDD',
    status: 'green', statusLabel: 'Green \u2014 In Progress',
    quarter: 'Q2', targetDate: 'Jul 31, 2026',
    description: 'Full redesign of the Commitment Report (CR) module in AEX — including COMBO CR across all suppliers, improved Excel export with TY item descriptions and offshore store highlighting, store summary graph improvements, and a Pre-Commit screen with unit presentation at fineline/color level. Enables download of multiple CR exports at once and UI to access previously generated reports.',
    businessBenefit: 'Reduces time buyers spend compiling and reformatting commitment reports for vendor communication. Combo CR eliminates the need to generate and merge multiple single-supplier reports.',
    techIntegration: 'Tracked across multiple OPIF/MTAP tickets. Key items: MTAP-9638 (CR multi-export, Backlog), MTAP-9879 (Pre-commit screen, Backlog). AEX CR module, store distribution data, and vendor communication workflows.',
    successMetrics: 'COMBO CR adopted as standard across all Fashion buying teams. Pre-commit screen live and reducing vendor miscommunication incidents. CR generation time reduced measurably.',
    owners: pptOwners('Brett Reid', 'TBD', 'Michael Allen'),
    resources: res('https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard'),
  },
  {
    id: 'shared-item-repository', title: 'Shared Item Repository (OneItem)', icon: '\uD83D\uDDC4\uFE0F',
    status: 'roadmap', statusLabel: 'Roadmap \u2014 Recommend & Optimize Phase',
    quarter: 'Q3', targetDate: 'Aug\u2013Oct 2026',
    description: 'Unified item repository serving as the single source of truth for Fashion product items across the E2E workflow — connecting AEX, Line Planning, Supplier Catalog, and item creation systems. Enables auto-population of line plan with potential items from Supplier Catalog through OneItem. Expanded sources include ROM, 3P data, and Circana retail signals.',
    businessBenefit: 'Eliminates duplicate item creation and conflicting item data across systems. Merchants select from a shared, AI-curated item repository rather than building items from scratch each season.',
    techIntegration: 'Jira: OPIF-325569 (Shared Item Repository). Integrates with AEX Assortment List, Supplier One catalog, OneItem workflow, and ISAM for item setup. Auto-populates LP with potential items. Circana, ROM, and 3P data feeds expand intelligence.',
    successMetrics: 'Shared Item Repository live and auto-populating line plans for target departments. Duplicate item creation rate eliminated. Item repository sourcing all ROM, 3P, and Circana signals confirmed.',
    owners: pptOwners('Brett Reid', 'TBD', 'Michael Allen'),
    resources: res('https://jira.walmart.com/browse/OPIF-325569'),
  },
  {
    id: 'global-buying-platform', title: 'Global Buying Capability', icon: '\uD83C\uDF0D',
    status: 'roadmap', statusLabel: 'Roadmap',
    quarter: 'Q4', targetDate: 'Nov 2026\u2013Jan 2027',
    description: 'Extension of the Fashion buying platform to support global segment needs — multi-currency, multi-market assortment planning and buy execution within AEX.',
    businessBenefit: 'International Fashion teams leverage the same buying workflow as domestic teams — eliminating global-specific tooling debt and enabling cross-market visibility.',
    techIntegration: 'AEX global capability requires multi-currency support, market-specific assortment logic, and integration with international supplier and item setup systems.',
    successMetrics: 'At least one global market piloted in AEX by end of Q4. Roadmap for remaining global markets defined and funded.',
    owners: TBD_OWNERS(), resources: res(),
  },
];