// data-design.js — Design pillar card definitions
// Depends on: data.js (own, res, TBD_OWNERS, pptOwners)

const CARDS_DESIGN = [
  {
    id: 'design-hub-centric', title: 'Launch Design Hub (Centric PLM)', icon: '\uD83C\uDFD7\uFE0F',
    status: 'green', statusLabel: 'On Track', quarter: 'Q1', targetDate: 'Q1 FY26',
    tag: 'Critical Program',
    description: 'Full launch of Centric PLM as the centralized Design Hub — replacing fragmented design tools with a single system of record for all Fashion product design and development.',
    businessBenefit: 'Design teams work in one system connected to buying and sourcing — eliminating handoff delays and duplicate data entry between disconnected tools.',
    techIntegration: 'Centric PLM is system of record for design. Contracts being finalized; integration plan covering AEX, Supplier One, and event layer in scope.',
    successMetrics: 'Contract signed and integration plan finalized. All target design teams onboarded. Design-to-buying handoff cycle time reduced.',
    owners: pptOwners('Chris Chiodo', '', ''), resources: res(),
  },
  {
    id: 'sample-mgmt-fit-eval', title: 'Sample Management & Fit Evaluation', icon: '\uD83D\uDCCB',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q1', targetDate: 'Q1\u2013Q2 FY26',
    tag: 'Critical Program',
    description: 'Streamlined sample management and fit evaluation workflow within Centric, eliminating manual tracking of physical samples and enabling structured fit feedback connected to design records.',
    businessBenefit: 'Sample review cycles are tracked, time-stamped, and linked to the product record — reducing duplicate sampling, missed fit issues, and approval delays.',
    techIntegration: 'Built within Centric PLM. Fit evaluation data connected to product spec record. Integration with sourcing calendar to enforce sample milestone gates.',
    successMetrics: 'All sample milestones tracked in Centric. Fit evaluation turnaround time reduced. Zero unreviewedsamples reaching production.',
    owners: pptOwners('Chris Chiodo', '', ''), resources: res(),
  },
  {
    id: 'line-planning', title: 'Line Planning & Calendar Management', icon: '\uD83D\uDCC5',
    status: 'green', statusLabel: 'Active', quarter: 'Q1', targetDate: 'Feb\u2013Apr 2026',
    description: 'End-to-end line planning and calendar management within Centric, connecting design decisions directly to buying and allocation workflows.',
    businessBenefit: 'Design teams plan against shared calendars that buying and allocation can see in real time — eliminating lag between design intent and downstream reaction.',
    techIntegration: 'Centric PLM is system of record for the line plan. Calendar milestones sync with AEX for buy readiness dates.',
    successMetrics: 'Line plan finalized and shared with Buying by target calendar milestone each season. Reduction in last-minute line plan changes after buying has begun.',
    owners: TBD_OWNERS(), resources: res(),
  },
  {
    id: 'product-specs', title: 'Product Specifications', icon: '\uD83D\uDCCB',
    status: 'green', statusLabel: 'Active', quarter: 'Q1', targetDate: 'Feb\u2013Apr 2026',
    description: 'Collaborative product specification management across design and sourcing — a single source of truth for product attributes in Centric.',
    businessBenefit: 'Eliminates spec re-entry across siloed tools. Design creates specs once; sourcing, buying, and item setup consume from the same record.',
    techIntegration: 'Centric product specs feed into item setup workflows and Supplier One for vendor distribution without manual redistribution.',
    successMetrics: 'Zero duplicate spec records across sourcing and item setup. Spec-related item setup errors reduced quarter over quarter.',
    owners: TBD_OWNERS(), resources: res(),
  },
  {
    id: 'trend-api-preseason', title: 'Trend API — 5+ Sources Pre-Season', icon: '\uD83D\uDD0D',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q2', targetDate: 'May\u2013Jul 2026',
    description: 'Launch of the Trend API with 5+ integrated trend sources specifically configured for pre-season use cases — giving designers and merchants multi-source trend consensus before line plans lock.',
    businessBenefit: 'Designers and merchants see a consolidated trend signal from multiple sources rather than triangulating manually, accelerating pre-season line plan decisions.',
    techIntegration: 'Trend API aggregates 5+ trend data providers. Signal surfaced in Centric and AEX line plan workflows via shared API layer.',
    successMetrics: 'Trend API live with 5+ sources in pre-season workflows. Adoption by target design teams confirmed. Pre-season line plan lock date achievedwithout trend reconciliation delays.',
    owners: pptOwners('Bill Chiodetti', '', ''), resources: res(),
  },
  {
    id: 'ap-tool-shared-ideation', title: 'AP Tool Shared Ideation & Integration', icon: '\uD83D\uDCA1',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q2', targetDate: 'May\u2013Jul 2026',
    description: 'Integration of AP Tool with Centric to enable shared ideation between Design and Buying — line plan concepts flow directly into the buying tool without manual handoff.',
    businessBenefit: 'Buying teams see design intent in real time during ideation — enabling earlier buy signal feedback that reduces late-stage line plan changes.',
    techIntegration: 'AP Tool line plan integration with Centric via shared event layer. Design ideation events in Centric trigger updates in AP Tool assortment view.',
    successMetrics: 'AP Tool and Centric sharing live line plan data. Reduction in design-to-buying handoff cycle time. Zero manual line plan exports between systems.',
    owners: pptOwners('Chris Chiodo', '', ''), resources: res(),
  },
  {
    id: 'ai-line-plan', title: 'AI-Enhanced Conceptual Line Plan', icon: '\uD83E\uDD16',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q2', targetDate: 'May\u2013Jul 2026',
    description: 'AI-powered conceptual line planning for merchants — using historical performance, trend signals, and financial guardrails to generate recommended line plan starting points.',
    businessBenefit: 'Merchants start each season with an AI-generated line plan framework, reducing blank-page planning time and anchoring decisions in data rather than intuition alone.',
    techIntegration: 'AI layer consumes Trend API, TTP financial targets, and AEX historical sell-through to generate conceptual line plan recommendations surfaced in Centric.',
    successMetrics: 'AI conceptual line plan adopted by target merchant groups. Planning cycle start time reduced. Merchants report improved confidence in opening line plan.',
    owners: pptOwners('Chris Chiodo', '', ''), resources: res(),
  },
  {
    id: 'fit-eval-workflow', title: 'Fit Evaluation Workflow Launch', icon: '\uD83D\uDC54',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q2', targetDate: 'May\u2013Jul 2026',
    description: 'Full launch of the Fit Evaluation workflow in Centric — structured, trackable fit feedback connected directly to the product specification record.',
    businessBenefit: 'Fit issues are identified and resolved earlier in the development calendar, reducing late-stage corrections that delay production and increase cost.',
    techIntegration: 'Centric fit evaluation workflow linked to product spec and sample management records. Fit approval status gates further design and sourcing steps.',
    successMetrics: 'Fit evaluation completed in Centric for all target categories. Fit-related production delays reduced. Fit approval-to-production lead time measurably shorter.',
    owners: pptOwners('Chris Chiodo', '', ''), resources: res(),
  },
  {
    id: 'centralized-dam', title: 'Centralized DAM Launch', icon: '\uD83D\uDDBC\uFE0F',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q2', targetDate: 'May\u2013Jul 2026',
    description: 'Launch of a centralized Digital Asset Management (DAM) system integrated with Centric, providing a single location for all product imagery, CAD files, and design assets.',
    businessBenefit: 'Eliminates asset duplication and version confusion across teams. Product imagery and design files are always current and findable without manual distribution.',
    techIntegration: 'DAM integrated with Centric PLM. Assets auto-linked to product records. CAD/2D/3D files accessible to vendors via Supplier One without email distribution.',
    successMetrics: 'All active design assets stored and managed in DAM. Zero duplicate asset versions across product teams. Asset retrieval time reduced significantly.',
    owners: pptOwners('Chris Chiodo', '', ''), resources: res(),
  },
  {
    id: 'centric-integration', title: 'Centric Integration Launch', icon: '\uD83D\uDD17',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q2', targetDate: 'May\u2013Jul 2026',
    description: 'Full Centric PLM integration launch connecting design records to AEX (buying), Supplier One (sourcing), and the shared event layer — closing the E2E design-to-execution loop.',
    businessBenefit: 'Design decisions in Centric automatically flow to buying, sourcing, and item setup — eliminating manual translation steps and the errors they introduce.',
    techIntegration: 'Centric integration covers AEX line plan sync, Supplier One spec distribution, DAM asset linking, and OneSource data feed. Event-driven architecture via shared integration layer.',
    successMetrics: 'All target Centric integrations live. Zero manual data exports from Centric to downstream systems for in-scope workflows.',
    owners: pptOwners('Chris Chiodo', '', ''), resources: res(),
  },
  {
    id: 'shared-event-layer', title: 'Shared Event Layer (AP, Centric, OneSource)', icon: '\uD83C\uDF10',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q2', targetDate: 'May\u2013Jul 2026',
    description: 'Integration of a shared event layer connecting AP Tool, Centric, and OneSource — enabling real-time data flow across Design, Buying, and Strategy systems without point-to-point coupling.',
    businessBenefit: 'System changes in one workstream tool propagate automatically to all connected systems. Eliminates the sync delays and manual reconciliation that occur with batch integrations.',
    techIntegration: 'Event-driven integration layer (likely Kafka or similar). AP Tool, Centric, and OneSource publish and consume events. Enables near-real-time cross-system state consistency.',
    successMetrics: 'Shared event layer live with all three systems publishing events. Cross-system data latency reduced to near real-time. Integration incident rate reduced.',
    owners: pptOwners('Chris Chiodo', '', ''), resources: res(),
  },
  {
    id: 'visual-boards', title: 'Centric Visual Board MVP', icon: '\uD83C\uDFA8',
    status: 'yellow', statusLabel: 'Yellow \u2014 June 15 Pilot',
    quarter: 'Q2', targetDate: 'Jun 15, 2026', tag: 'Critical Program',
    description: 'Visual Boards in Centric — a collaborative visual workspace replacing Miro, integrated directly into the Fashion E2E ecosystem with live product data.',
    businessBenefit: 'Design teams gain a visual assortment planning workspace natively connected to Centric data — no more exporting to Miro and losing the link to the actual plan.',
    techIntegration: 'Built natively within Centric PLM. Visual boards pull live product imagery, color, and spec data from Centric records. No separate sync required.',
    pathToGreen: 'Finalizing contracts with Centric to secure onboarding lead time. Investigating pulling pilot date into end of May.',
    successMetrics: 'Miro usage for assortment visualization retired by end of pilot. Design review cycle time reduced. Associate adoption > 80% within first season.',
    owners: TBD_OWNERS(), resources: res(),
  },
  {
    id: 'material-sourcing', title: 'Material & Sourcing Management', icon: '\uD83E\uDDF5',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q3', targetDate: 'Aug\u2013Oct 2026',
    description: 'Material and sourcing workflow integration connecting design decisions to sourcing execution without manual handoffs via email or spreadsheet.',
    businessBenefit: 'Design material decisions in Centric automatically trigger sourcing workflows — eliminating email handoffs and reducing lead time from design approval to vendor engagement.',
    techIntegration: 'Planned integration between Centric (material records) and Supplier One (vendor workflows) via the Integration & Connection Services layer.',
    successMetrics: 'Zero manual email handoffs for approved material decisions. Sourcing receives structured data, not PDFs.',
    owners: TBD_OWNERS(), resources: res(),
  },
  {
    id: 'design-analytics', title: 'Advanced Design Analytics', icon: '\uD83D\uDCCA',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q4', targetDate: 'Nov 2026\u2013Jan 2027',
    description: 'Analytics capabilities within Centric enabling design teams to make data-informed decisions about color, trend, and product performance across seasons.',
    businessBenefit: 'Connects historical sales and trend data to design decisions — reducing reliance on intuition and improving line plan accuracy season over season.',
    techIntegration: 'Centric analytics pulls from AEX sell-through data, TTP strategic priorities, and external trend data sources via the integration layer.',
    successMetrics: 'Design teams using analytics for >50% of key product decisions. Measurable improvement in new product success rate vs. prior seasons.',
    owners: TBD_OWNERS(), resources: res(),
  },
];