// data-design.js — Design pillar card definitions
// Source: Confluence LLTT Work Management Dashboard (APREC space)
// Live Jira data: https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard
// Depends on: data.js (own, res, TBD_OWNERS, pptOwners)

const CARDS_DESIGN = [
  {
    id: 'design-hub-centric', title: 'Launch Design Hub (Centric PLM)', icon: '\uD83C\uDFD7\uFE0F',
    status: 'green', statusLabel: 'On Track', quarter: 'Q1', targetDate: 'Q1 FY27',
    tag: 'Critical Program',
    description: 'Full launch of Centric PLM as the centralized Design Hub — replacing fragmented design tools with a single system of record for all Fashion product design and development. Includes milestone review of Centric capabilities and ownership proposal for workflows in Centric vs. AP Tool vs. OneSource. Milestone OPIF-347498: COMPLETE — Milestone Only. Christopher has stated that this is now complete. Milestone OPIF-347500: Backlog — Full verticals and ownership review with proposal pending. Assignee: Christopher Chiodo.',
    businessBenefit: 'Design teams work in one system connected to buying and sourcing — eliminating handoff delays and duplicate data entry between disconnected tools. Deprecates Bamboo Rose and eliminates Miro dependency for assortment visualization. Centric becomes the single source of truth for all product design, specification, and sample management.',
    techIntegration: 'Primary OPIF: OPIF-325208 (Design Hub — Centric Integration). Related: OPIF-347498 (Milestone: Centric capabilities review vs AP Tool vs OneSource — DONE), OPIF-347500 (Milestone: Full verticals and ownership proposal — Backlog), OPIF-325206 (Shared Merch Strategy). Centric PLM is system of record for design. Integration plan covers AEX line plan sync, Supplier One spec distribution, DAM asset linking, and OneSource data feed via shared event layer. PRD: OneSource Design Integration (IESP Confluence space).',
    successMetrics: 'Contract signed and integration plan finalized. All target design teams onboarded to Centric. Bamboo Rose decommissioned. Design-to-buying handoff cycle time reduced. Milestone OPIFs (347498, 347500) both completed and proposals actioned.',
    owners: pptOwners('Tammy Hawkins', 'Ramesh Simhambhatla', 'Christopher Chiodo', 'Stephen Wolf', ''),
    resources: res(
      'https://jira.walmart.com/browse/OPIF-325208',
      '#',
      'https://confluence.walmart.com/display/IESP/PRD+-+OneSource+Design+Integration',
      '#',
      [
        { label: 'OPIF-325208 — Design Hub (Centric Integration) — Primary', url: 'https://jira.walmart.com/browse/OPIF-325208' },
        { label: 'OPIF-347498 — Milestone: Centric Capabilities Review (DONE)', url: 'https://jira.walmart.com/browse/OPIF-347498' },
        { label: 'OPIF-347500 — Milestone: Full Verticals & Ownership Review (Related)', url: 'https://jira.walmart.com/browse/OPIF-347500' },
        { label: 'OPIF-325206 — Shared Merch Strategy (Related)', url: 'https://jira.walmart.com/browse/OPIF-325206' },
        { label: 'PRD: OneSource Design Integration (Confluence IESP)', url: 'https://confluence.walmart.com/display/IESP/PRD+-+OneSource+Design+Integration' },
        { label: 'LLTT Dashboard', url: 'https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard' },
      ]
    ),
    workstreams: ['design', 'strategy'],
  },
  {
    id: 'aex-lineplan-migration', title: 'AEX Line Plan Migration to AP Tool', icon: '\uD83D\uDD04',
    status: 'yellow', statusLabel: 'Yellow \u2014 Work in Progress',
    quarter: 'Q3', targetDate: 'July 31, 2026',
    tag: 'Critical Program',
    jiraStatus: 'Work in Progress',
    priority: 'P3',
    techRank: 5,
    description: 'Migration of the AEX Fashion Line Planning experience to the AP Tool Assortment List — replacing the legacy line plan module with AP Plan Creation & Plan List. Includes enabling fashion-specific metrics, attributes, Excel upload reuse, and potential item population via Item Repository and OneItem workflow. Merchants get out of Excel permanently. Jira update (Mar 3, 2026): 03-Mar-2026 - Next Step: There is a 2 week spike stories and scope will be confirmed.  (ETA: 16-Mar). Timeline to be finalize post this spike ||Deliverables||Timeline || |Planned Start Date|17-Feb| |Development Complete|19-Feb| |QE Functional / Integ Path to Green: Working with Ashwin to get LOE.. Status: Work in Progress. Assignee: Ashwin Chidambaram.',
    businessBenefit: 'Eliminates dual-system line planning (Excel + AEX). Merchants plan in one connected environment from line intent through to buy execution. Fashion attribute and metric enablement accelerates downstream buying decisions. Excel upload reuse eliminates re-keying of potential items from Supplier Catalog.',
    techIntegration: 'Primary OPIF: OPIF-325568 (Move Fashion Line Planning to AP Tool Assortment List — Work in Progress, Q2 FY27). Related OPIFs: OPIF-325216 (AEX Fashion: Use AP Plan Creation & Plan List — Initial Requirements), OPIF-325217 (Fashion Metrics Enablement in Assortment List and Downstream Validation), OPIF-325565 (Fashion Re-Use of Assortment Planning Potential Item Excel Upload — Initial Requirements), OPIF-337970 (Auto-populate Line Plan with Potential Items from Supplier Catalog — Backlog). AP Tool Assortment List becomes Fashion line plan system of record. Auto-populate from Supplier Catalog via Item Repository/OneItem workflow. PRD: Transition Plan Creation and Line Planning to Assortment Planning (Confluence APREC).',
    successMetrics: 'Fashion Line Planning 100% migrated to AP Tool Assortment List. Excel-based line plan workarounds eliminated. Fashion metrics and attributes fully enabled in Assortment List. Item auto-population from Supplier Catalog via Item Repository live. Zero manual re-key of potential items.',
    owners: pptOwners('Brett Reid', 'Ashwin Chidambaram', 'Taylor Watson', 'CJ Weatherford', 'Arun Santhiagu'),
    resources: res(
      'https://jira.walmart.com/browse/OPIF-325568',
      '#',
      'https://confluence.walmart.com/display/APREC/Transition+Plan+Creation+and+Line+Planning+to+Assortment+Planning',
      '#',
      [
        { label: 'OPIF-325568 — Move Fashion Line Planning to AP Tool Assortment List (Primary — WIP)', url: 'https://jira.walmart.com/browse/OPIF-325568' },
        { label: 'OPIF-325216 — AEX Fashion: Use AP Plan Creation & Plan List (Related)', url: 'https://jira.walmart.com/browse/OPIF-325216' },
        { label: 'OPIF-325217 — Fashion Metrics Enablement in Assortment List (Related)', url: 'https://jira.walmart.com/browse/OPIF-325217' },
        { label: 'OPIF-325565 — Fashion Re-Use of AP Potential Item Excel Upload (Related)', url: 'https://jira.walmart.com/browse/OPIF-325565' },
        { label: 'OPIF-337970 — Auto-populate Line Plan from Supplier Catalog (Related)', url: 'https://jira.walmart.com/browse/OPIF-337970' },
        { label: 'PRD: Transition Plan Creation & Line Planning to AP (Confluence APREC)', url: 'https://confluence.walmart.com/display/APREC/Transition+Plan+Creation+and+Line+Planning+to+Assortment+Planning' },
        { label: 'LLTT Dashboard', url: 'https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard' },
      ]
    ),
    workstreams: ['design', 'buying'],
  },
  {
    id: 'sample-mgmt-fit-eval', title: 'Sample Management & Fit Evaluation', icon: '\uD83D\uDCCB',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q1', targetDate: 'Q1\u2013Q2 FY27',
    tag: 'Critical Program',
    description: 'Streamlined sample management and fit evaluation workflow within Centric, eliminating manual tracking of physical samples and enabling structured fit feedback connected to design records.',
    businessBenefit: 'Sample review cycles are tracked, time-stamped, and linked to the product record — reducing duplicate sampling, missed fit issues, and approval delays.',
    techIntegration: 'Built within Centric PLM. Fit evaluation data connected to product spec record. Integration with sourcing calendar to enforce sample milestone gates.',
    successMetrics: 'All sample milestones tracked in Centric. Fit evaluation turnaround time reduced. Zero unreviewedsamples reaching production.',
    owners: pptOwners('Tammy Hawkins', 'Ramesh Simhambhatla', 'Christopher Chiodo', 'Stephen Wolf', ''), resources: res(), workstreams: ['design'],
  },
  {
    id: 'line-planning', title: 'Line Planning & Calendar Management', icon: '\uD83D\uDCC5',
    status: 'green', statusLabel: 'Active', quarter: 'Q1', targetDate: 'Feb\u2013Apr 2026',
    description: 'End-to-end line planning and calendar management within Centric, connecting design decisions directly to buying and allocation workflows.',
    businessBenefit: 'Design teams plan against shared calendars that buying and allocation can see in real time — eliminating lag between design intent and downstream reaction.',
    techIntegration: 'Centric PLM is system of record for the line plan. Calendar milestones sync with AEX for buy readiness dates.',
    successMetrics: 'Line plan finalized and shared with Buying by target calendar milestone each season. Reduction in last-minute line plan changes after buying has begun.',
    owners: pptOwners('Tammy Hawkins', 'Ramesh Simhambhatla', 'Christopher Chiodo', 'Stephen Wolf', ''), resources: res(), workstreams: ['design', 'buying'],
  },
  {
    id: 'product-specs', title: 'Product Specifications', icon: '\uD83D\uDCCB',
    status: 'green', statusLabel: 'Active', quarter: 'Q1', targetDate: 'Feb\u2013Apr 2026',
    description: 'Collaborative product specification management across design and sourcing — a single source of truth for product attributes in Centric.',
    businessBenefit: 'Eliminates spec re-entry across siloed tools. Design creates specs once; sourcing, buying, and item setup consume from the same record.',
    techIntegration: 'Centric product specs feed into item setup workflows and Supplier One for vendor distribution without manual redistribution.',
    successMetrics: 'Zero duplicate spec records across sourcing and item setup. Spec-related item setup errors reduced quarter over quarter.',
    owners: pptOwners('Tammy Hawkins', 'Ramesh Simhambhatla', 'Christopher Chiodo', 'Stephen Wolf', ''), resources: res(), workstreams: ['design'],
  },
  {
    id: 'trend-api-preseason', title: 'Trend API — 5+ Sources Pre-Season', icon: '\uD83D\uDD0D',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q2', targetDate: 'May\u2013Jul 2026',
    description: 'Launch of the Trend API with 5+ integrated trend sources specifically configured for pre-season use cases — giving designers and merchants multi-source trend consensus before line plans lock.',
    businessBenefit: 'Designers and merchants see a consolidated trend signal from multiple sources rather than triangulating manually, accelerating pre-season line plan decisions.',
    techIntegration: 'Trend API aggregates 5+ trend data providers. Signal surfaced in Centric and AEX line plan workflows via shared API layer.',
    successMetrics: 'Trend API live with 5+ sources in pre-season workflows. Adoption by target design teams confirmed. Pre-season line plan lock date achievedwithout trend reconciliation delays.',
    owners: pptOwners('Bill Chiodetti', 'Ramesh Simhambhatla', '', 'Leon Hovanesian', ''), resources: res(), workstreams: ['design', 'strategy'],
  },
  {
    id: 'ap-tool-shared-ideation', title: 'AP Tool Shared Ideation & Integration', icon: '\uD83D\uDCA1',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q2', targetDate: 'May\u2013Jul 2026',
    description: 'Integration of AP Tool with Centric to enable shared ideation between Design and Buying — line plan concepts flow directly into the buying tool without manual handoff.',
    businessBenefit: 'Buying teams see design intent in real time during ideation — enabling earlier buy signal feedback that reduces late-stage line plan changes.',
    techIntegration: 'AP Tool line plan integration with Centric via shared event layer. Design ideation events in Centric trigger updates in AP Tool assortment view.',
    successMetrics: 'AP Tool and Centric sharing live line plan data. Reduction in design-to-buying handoff cycle time. Zero manual line plan exports between systems.',
    owners: pptOwners('Brett Reid', 'Ashwin Chidambaram', 'Taylor Watson', 'CJ Weatherford', 'Arun Santhiagu'), resources: res(), workstreams: ['design', 'buying'],
  },
  {
    id: 'ai-line-plan', title: 'AI-Enhanced Conceptual Line Plan', icon: '\uD83E\uDD16',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q2', targetDate: 'May\u2013Jul 2026',
    description: 'AI-powered conceptual line planning for merchants — using historical performance, trend signals, and financial guardrails to generate recommended line plan starting points.',
    businessBenefit: 'Merchants start each season with an AI-generated line plan framework, reducing blank-page planning time and anchoring decisions in data rather than intuition alone.',
    techIntegration: 'AI layer consumes Trend API, TTP financial targets, and AEX historical sell-through to generate conceptual line plan recommendations surfaced in Centric.',
    successMetrics: 'AI conceptual line plan adopted by target merchant groups. Planning cycle start time reduced. Merchants report improved confidence in opening line plan.',
    owners: pptOwners('Bill Chiodetti', 'Ramesh Simhambhatla', 'Christopher Chiodo', 'Leon Hovanesian', ''), resources: res(), workstreams: ['design', 'strategy'],
  },
  {
    id: 'fit-eval-workflow', title: 'Fit Evaluation Workflow Launch', icon: '\uD83D\uDC54',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q2', targetDate: 'May\u2013Jul 2026',
    description: 'Full launch of the Fit Evaluation workflow in Centric — structured, trackable fit feedback connected directly to the product specification record.',
    businessBenefit: 'Fit issues are identified and resolved earlier in the development calendar, reducing late-stage corrections that delay production and increase cost.',
    techIntegration: 'Centric fit evaluation workflow linked to product spec and sample management records. Fit approval status gates further design and sourcing steps.',
    successMetrics: 'Fit evaluation completed in Centric for all target categories. Fit-related production delays reduced. Fit approval-to-production lead time measurably shorter.',
    owners: pptOwners('Tammy Hawkins', 'Ramesh Simhambhatla', 'Christopher Chiodo', 'Stephen Wolf', ''), resources: res(), workstreams: ['design'],
  },
  {
    id: 'centralized-dam', title: 'Centralized DAM Launch', icon: '\uD83D\uDDBC\uFE0F',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q2', targetDate: 'May\u2013Jul 2026',
    description: 'Launch of a centralized Digital Asset Management (DAM) system integrated with Centric, providing a single location for all product imagery, CAD files, and design assets.',
    businessBenefit: 'Eliminates asset duplication and version confusion across teams. Product imagery and design files are always current and findable without manual distribution.',
    techIntegration: 'DAM integrated with Centric PLM. Assets auto-linked to product records. CAD/2D/3D files accessible to vendors via Supplier One without email distribution.',
    successMetrics: 'All active design assets stored and managed in DAM. Zero duplicate asset versions across product teams. Asset retrieval time reduced significantly.',
    owners: pptOwners('Tammy Hawkins', 'Ramesh Simhambhatla', 'Christopher Chiodo', 'Stephen Wolf', ''), resources: res(), workstreams: ['design'],
  },
  {
    id: 'centric-integration', title: 'Centric Integration Launch', icon: '\uD83D\uDD17',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q2', targetDate: 'May\u2013Jul 2026',
    description: 'Full Centric PLM integration launch connecting design records to AEX (buying), Supplier One (sourcing), and the shared event layer — closing the E2E design-to-execution loop.',
    businessBenefit: 'Design decisions in Centric automatically flow to buying, sourcing, and item setup — eliminating manual translation steps and the errors they introduce.',
    techIntegration: 'Centric integration covers AEX line plan sync, Supplier One spec distribution, DAM asset linking, and OneSource data feed. Event-driven architecture via shared integration layer.',
    successMetrics: 'All target Centric integrations live. Zero manual data exports from Centric to downstream systems for in-scope workflows.',
    owners: pptOwners('Tammy Hawkins', 'Ramesh Simhambhatla', 'Christopher Chiodo', 'Stephen Wolf', ''), resources: res(), workstreams: ['design', 'buying'],
  },
  {
    id: 'shared-event-layer', title: 'Shared Event Layer (AP, Centric, OneSource)', icon: '\uD83C\uDF10',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q2', targetDate: 'May\u2013Jul 2026',
    description: 'Integration of a shared event layer connecting AP Tool, Centric, and OneSource — enabling real-time data flow across Design, Buying, and Strategy systems without point-to-point coupling. OPIF-325188 (Shared Project Tracking and Event Calendar) establishes the tracking and calendar scaffolding. OPIF-325188 Status: Initial Requirements. Assignee: Christopher Chiodo. Reporter: Christopher Chiodo. Component: US Omni Tech - AEX-FashionApparel.',
    businessBenefit: 'System changes in one workstream tool propagate automatically to all connected systems. Eliminates the sync delays and manual reconciliation that occur with batch integrations. Shared event calendar ensures all tools reflect the same planning milestones simultaneously.',
    techIntegration: 'Primary OPIF: OPIF-325188 (Shared Project Tracking and Event Calendar — Initial Requirements). Related: OPIF-325208 (Design Hub / Centric Integration), OPIF-325203 (Shared Item Repository). Event-driven integration layer. AP Tool, Centric, and OneSource publish and consume events. Enables near-real-time cross-system state consistency. PRD: Confluence APREC space (pageId 3255372152).',
    successMetrics: 'Shared event layer live with all three systems publishing events. Cross-system data latency reduced to near real-time. Integration incident rate reduced. Shared event calendar live and consumed by AP, Centric, and OneSource.',
    owners: pptOwners('Tammy Hawkins', 'Ramesh Simhambhatla', 'Christopher Chiodo', 'Stephen Wolf', ''),
    resources: res(
      'https://jira.walmart.com/browse/OPIF-325188',
      '#',
      'https://confluence.walmart.com/pages/viewpage.action?pageId=3255372152',
      '#',
      [
        { label: 'OPIF-325188 — Shared Project Tracking and Event Calendar (Primary)', url: 'https://jira.walmart.com/browse/OPIF-325188' },
        { label: 'OPIF-325208 — Design Hub (Centric Integration) (Related)', url: 'https://jira.walmart.com/browse/OPIF-325208' },
        { label: 'OPIF-325203 — Shared Item Repository (Related)', url: 'https://jira.walmart.com/browse/OPIF-325203' },
        { label: 'PRD: Shared Project Tracking & Event Calendar (Confluence)', url: 'https://confluence.walmart.com/pages/viewpage.action?pageId=3255372152' },
        { label: 'LLTT Dashboard', url: 'https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard' },
      ]
    ),
    workstreams: ['design', 'buying', 'strategy'],
  },
  {
    id: 'visual-boards', title: 'Centric Visual Board MVP', icon: '\uD83C\uDFA8',
    status: 'yellow', statusLabel: 'Yellow \u2014 Trending Green',
    quarter: 'Q2', targetDate: 'End of May 2026', tag: 'Critical Program',
    description: 'Visual Boards in Centric — a collaborative visual workspace that deprecates Bamboo Rose and moves design teams off Miro, centralizing fit management and visual assortment planning directly in the Centric platform with live product data. Critical path: Centric contract finalization required (12-week onboarding lead time). Milestone OPIF-347498: COMPLETE — Milestone Only. Christopher has stated that this is now complete. Milestone OPIF-347500: Backlog — Full verticals and ownership review with proposal pending. Assignee: Christopher Chiodo.',
    businessBenefit: 'Deprecates Bamboo Rose and eliminates Miro dependency. Design teams gain a visual assortment planning workspace natively connected to Centric data — decisions are traceable and always linked to the actual plan, not a disconnected whiteboard export. End-of-May 2026 pilot target once contracts signed.',
    techIntegration: 'Primary OPIF: OPIF-325208 (Design Hub — Centric Integration). Related: OPIF-347498 (Milestone: Centric Capabilities Review — DONE), OPIF-347500 (Milestone: Full Verticals & Ownership Review). Built natively within Centric PLM. Visual boards pull live product imagery, color, and spec data from Centric records. No separate sync required. Replaces Bamboo Rose and Miro for all in-scope design workflows. PRD: OneSource Design Integration (Confluence IESP).',
    pathToGreen: 'Finalize contracts with Centric by target date to secure required 12-week onboarding lead time. Contract finalization is the critical path item — once signed, pilot launch moves to end of May 2026.',
    successMetrics: 'Bamboo Rose decommissioned. Miro usage for assortment visualization retired by end of pilot. Design review cycle time reduced. Associate adoption > 80% within first season.',
    owners: pptOwners('Tammy Hawkins', 'Ramesh Simhambhatla', 'Christopher Chiodo', 'Stephen Wolf', ''),
    resources: res(
      'https://jira.walmart.com/browse/OPIF-325208',
      '#',
      'https://confluence.walmart.com/display/IESP/PRD+-+OneSource+Design+Integration',
      '#',
      [
        { label: 'OPIF-325208 — Design Hub (Centric Integration) — Primary', url: 'https://jira.walmart.com/browse/OPIF-325208' },
        { label: 'OPIF-347498 — Milestone: Centric Capabilities Review (DONE)', url: 'https://jira.walmart.com/browse/OPIF-347498' },
        { label: 'OPIF-347500 — Milestone: Full Verticals & Ownership Review', url: 'https://jira.walmart.com/browse/OPIF-347500' },
        { label: 'PRD: OneSource Design Integration (Confluence IESP)', url: 'https://confluence.walmart.com/display/IESP/PRD+-+OneSource+Design+Integration' },
        { label: 'LLTT Dashboard', url: 'https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard' },
      ]
    ),
    workstreams: ['design'],
  },
  {
    id: 'material-sourcing', title: 'Material & Sourcing Management', icon: '\uD83E\uDDF5',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q3', targetDate: 'Aug\u2013Oct 2026',
    description: 'Material and sourcing workflow integration connecting design decisions to sourcing execution without manual handoffs via email or spreadsheet.',
    businessBenefit: 'Design material decisions in Centric automatically trigger sourcing workflows — eliminating email handoffs and reducing lead time from design approval to vendor engagement.',
    techIntegration: 'Planned integration between Centric (material records) and Supplier One (vendor workflows) via the Integration & Connection Services layer.',
    successMetrics: 'Zero manual email handoffs for approved material decisions. Sourcing receives structured data, not PDFs.',
    owners: pptOwners('Tammy Hawkins', 'Ramesh Simhambhatla', 'Christopher Chiodo', 'Stephen Wolf', ''), resources: res(), workstreams: ['design'],
  },
  {
    id: 'design-analytics', title: 'Advanced Design Analytics', icon: '\uD83D\uDCCA',
    status: 'roadmap', statusLabel: 'Roadmap', quarter: 'Q4', targetDate: 'Nov 2026\u2013Jan 2027',
    description: 'Analytics capabilities within Centric enabling design teams to make data-informed decisions about color, trend, and product performance across seasons.',
    businessBenefit: 'Connects historical sales and trend data to design decisions — reducing reliance on intuition and improving line plan accuracy season over season.',
    techIntegration: 'Centric analytics pulls from AEX sell-through data, TTP strategic priorities, and external trend data sources via the integration layer.',
    successMetrics: 'Design teams using analytics for >50% of key product decisions. Measurable improvement in new product success rate vs. prior seasons.',
    owners: pptOwners('Bill Chiodetti', 'Ramesh Simhambhatla', 'Christopher Chiodo', 'Leon Hovanesian', ''), resources: res(), workstreams: ['design', 'strategy'],
  },
];