// data-buying.js — Buying pillar card definitions
// Source: Confluence LLTT Work Management Dashboard (APREC space)
// Live Jira: https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard
// Depends on: data.js (own, res, TBD_OWNERS, pptOwners)

const CARDS_BUYING = [
  {
    id: 'neo-replatform', title: 'AEX Replatform \u2014 Neo', icon: '\uD83C\uDFC6',
    status: 'completed', statusLabel: 'Completed', quarter: 'completed',
    targetDate: 'Mar 2, 2026', tag: 'Major Win',
    description: 'All AEX Fashion departments migrated to the Neo platform (D23, D25, D34 final). Re-architected backend integration layer — 700+ automated test cases, 360+ issues resolved. Now in Hypercare.',
    businessBenefit: '50% reduction in support tickets YoY. 1\u20132 day deployment cycles (down from 4\u20135 days). Foundation for all future AEX capability delivery.',
    techIntegration: 'Replaced legacy integration layer with modern resilient architecture. Automation via MCP Playwright with 99% automatable E2E test cases. Q1 prioritized backlog: 6 Fast Follows, 15 Stability, 3 Transformation items.',
    successMetrics: 'Support ticket volume down 50% YoY. Deployment cycle 1\u20132 days. Zero data-loss incidents on platform transition.',
    owners: pptOwners('Brett Reid', 'Chris Graves', 'Ryan Henderson', 'Robbie Dutta', 'Mike Dunn'), resources: res(), workstreams: ['buying'],
  },
  {
    id: 'aex-stability', title: 'AEX Stability & Quality of Life', icon: '\uD83D\uDEE1\uFE0F',
    critical: true,
    status: 'green', statusLabel: 'Green \u2014 Q1 Improvements',
    quarter: 'Q1', targetDate: 'April 30, 2026', tag: 'Critical Program',
    description: 'Q1 stability improvements delivering measurable impact across the AEX platform. Executing platform transition with zero data loss. Activating confirmation safeguards for fineline and style deletions — preventing accidental data loss. Unifying size ordering across Size & Pack and automating online item creation and new store POs. Of 24 prioritized OPIFs: 18 Green, 5 Yellow, 1 Red. Key MTAP tickets in WIP: MTAP-9154, MTAP-7474, MTAP-7438, MTAP-6808, MTAP-9541, MTAP-9570, MTAP-9543.',
    businessBenefit: 'Merchants gain confidence that AEX decisions execute correctly — safeguards prevent accidental deletions, unified size ordering eliminates inconsistencies, and automated new-store POs remove manual work from the buying workflow.',
    techIntegration: 'Q1 Stability tracked across 24 OPIFs in the LLTT Jira initiative. Key featured OPIFs: OPIF-344926 (AEX Automated Item Set Up — walkthroughs underway), OPIF-325602 (Tagging & Affinity Graph — ready for sizing), OPIF-325568 (Move Fashion LP to AP Tool — WIP). Active bug fixes tracked as PRB incidents in MTAP project (MTAP-9154, MTAP-7474, MTAP-7438, MTAP-6808, MTAP-9541, MTAP-9570, MTAP-9543). LLTT Dashboard tracks full OPIF portfolio.',
    successMetrics: 'All 24 OPIFs resolved or committed. Merchant satisfaction score improves. Support ticket volume continues downward trend from Neo baseline.',
    owners: pptOwners('Brett Reid', 'Chris Graves', 'Ryan Henderson', 'Robbie Dutta', 'Mike Dunn'),
    resources: res(
      'https://jira.walmart.com/browse/OPIF-344926',
      '#',
      'https://confluence.walmart.com/display/APREC/Automated+Item+Set+Up+for+AEX+Intents',
      '#',
      [
        { label: 'OPIF-344926 — AEX Automated Item Set Up (Q1 Featured — Primary)', url: 'https://jira.walmart.com/browse/OPIF-344926' },
        { label: 'OPIF-325602 — Tagging & Affinity Graph (Q1 Featured)', url: 'https://jira.walmart.com/browse/OPIF-325602' },
        { label: 'OPIF-325568 — Move Fashion LP to AP Tool (Q1 Featured)', url: 'https://jira.walmart.com/browse/OPIF-325568' },
        { label: 'LLTT Dashboard (all 24 Stability OPIFs)', url: 'https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard' },
      ]
    ),
    workstreams: ['buying'],
  },
  {
    id: 'auto-item-setup', title: 'Automated Item Setup', icon: '\u2699\uFE0F',
    critical: true,
    status: 'yellow', statusLabel: 'Yellow \u2014 Ready to Start (P1 \u26a0\ufe0f)',
    quarter: 'Q2', targetDate: 'April 30, 2026', tag: 'Critical Program',
    jiraStatus: 'Pending Sizing',
    priority: 'P1',
    techRank: 1,
    description: '\u2705 OPIF-mapped \u2014 auto-syncs with Jira. 3 pillars all on track: (1) Gen AI Data Enrichment, (2) Parent Anchored Variant Groups, (3) Seamless Data Flow (AEX \u2192 Item). Removes merchant execution from item setup and PO creation once assortment decisions are finalized in AEX. Captures merchant intent upfront \u2014 eliminating re-entry loops and supplier clarification cycles. Exception management shifted to IDC team (human-in-the-loop model). Jira update (Mar 20, 2026): OPIF-344926 is now in Pending Sizing status with P1 Priority. Walkthroughs are underway and ready for sizing. Leadership-mandated deadline: April 30, 2026. Assignee: Abhishek Jannawar.',
    businessBenefit: 'Removes manual item setup work from Fashion Merchants entirely. Merchant intent captured once in AEX; IDC team owns exceptions. Estimated to save hundreds of hours per season across the merchant organization. Gen AI data enrichment ensures item attributes are complete and accurate without merchant intervention. Leadership-mandated April 30, 2026 deadline signals top executive priority — must-deliver for FY27.',
    techIntegration: 'Primary OPIF: OPIF-344926 (AEX — Automated Item Set Up — Walkthroughs underway, target April 30 2026). AEX captures assortment intent and triggers automated item setup via integration with ISAM, Supplier One, and item setup systems. IDC handles exceptions through a managed queue. Gen AI enrichment layer processes item data before submission. PRD: Automated Item Set Up for AEX Intents (Confluence APREC).',
    pathToGreen: 'Next Steps: Finalize engineering timelines for Supplier One and ISAM capabilities to resolve remaining merchant pain points.',
    successMetrics: 'Automated item setup rate >90% of eligible items. Merchant time on manual item setup reduced to near zero. PO creation cycle time reduced from days to hours.',
    owners: pptOwners('Brett Reid', 'Chris Graves', 'Abhishek Jannawar', 'Robbie Dutta', 'Mike Dunn'),
    resources: res(
      'https://jira.walmart.com/browse/OPIF-344926',
      '#',
      'https://confluence.walmart.com/display/APREC/Automated+Item+Set+Up+for+AEX+Intents',
      '#',
      [
        { label: 'OPIF-344926 — AEX Automated Item Set Up (Primary)', url: 'https://jira.walmart.com/browse/OPIF-344926' },
        { label: 'PRD: Automated Item Set Up for AEX Intents (Confluence APREC)', url: 'https://confluence.walmart.com/display/APREC/Automated+Item+Set+Up+for+AEX+Intents' },
        { label: 'LLTT Dashboard', url: 'https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard' },
      ]
    ),
    workstreams: ['buying'],
  },
  {
    id: 'fashion-fixture-allocation-buying', title: 'Fashion Fixture Allocation (Visual)', icon: '\uD83C\uDFEA',
    status: 'green', statusLabel: 'Green \u2014 In Discovery',
    quarter: 'Q2', targetDate: 'Jul 31, 2026',
    description: 'Assisted Fixture Allocation capability enabling merchants to plan product placement across store fixtures with an AI-assisted visual interface — requirements gathering underway. Builds on tagging and affinity graph data as a foundation. PRD in progress. Scope planning note: Corresponding with Dhaarna to determine if this OPIF is anticipated to be worked on in Q1. It\'s a maybe, but will move it to Q2 for now and if capacity allows for it, we can plan it back into Q1. OPIF-325598 Status: PRD In Progress. Related: OPIF-325599 (Category Space Planning) — Status: Backlog, Assignee: Dhaarna Singh.',
    businessBenefit: 'Merchants can visualize and optimize fixture allocation without complex spreadsheets, leading to better product placement decisions and fewer fixture conflicts. AI assistance surfaces recommended assortments per fixture based on tagging and affinity data — reducing manual merchant judgment burden.',
    techIntegration: 'Primary OPIF: OPIF-325598 (Assisted Fixture Allocation and Recommendations — Requirements gathering underway). Related: OPIF-325599 (Category Space Planning & Dynamic In-season Execution — Backlog, Dhaarna Singh), OPIF-325602 (Tagging and Affinity Graph — foundation). Integrates with AEX assortment data for product-to-fixture mapping and with store planogram systems. Builds on tagging taxonomy and affinity graph from tagging pilot. PRD: Confluence APREC space.',
    successMetrics: 'Assisted fixture allocation adopted across target departments. Fixture conflicts reduced. Merchant fixture planning time measurably reduced. AI recommendation acceptance rate tracked and improving.',
    owners: pptOwners('Brett Reid', 'Sakshi Datta', 'Dhaarna Singh', 'Minwoo Kim', ''),
    resources: res(
      'https://jira.walmart.com/browse/OPIF-325598',
      '#',
      'https://confluence.walmart.com/pages/viewpage.action?pageId=3261566926',
      '#',
      [
        { label: 'OPIF-325598 — Assisted Fixture Allocation and Recommendations (Primary)', url: 'https://jira.walmart.com/browse/OPIF-325598' },
        { label: 'OPIF-325599 — Category Space Planning & Dynamic In-season Execution (Related)', url: 'https://jira.walmart.com/browse/OPIF-325599' },
        { label: 'OPIF-325602 — Tagging and Affinity Graph (Foundation)', url: 'https://jira.walmart.com/browse/OPIF-325602' },
        { label: 'PRD: Assisted Fixture Allocation (Confluence APREC)', url: 'https://confluence.walmart.com/pages/viewpage.action?pageId=3261566926' },
        { label: 'LLTT Dashboard', url: 'https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard' },
      ]
    ),
    workstreams: ['buying'],
  },
  {
    id: 'ai-item-repository', title: 'AI Item Repository Launch', icon: '\uD83E\uDDE0',
    status: 'green', statusLabel: 'Green \u2014 In Discovery',
    quarter: 'Q2', targetDate: 'Jul 31, 2026',
    description: 'AI-powered item repository providing merchants with intelligent product reuse recommendations — surfacing relevant historical items via the Supplier Catalog through the Item Repository/OneItem workflow. Enables auto-population of line plan with potential items. Requirements gathering underway. Jira: OPIF-337970 (Backlog, Ryan Henderson).',
    businessBenefit: 'Reduces time spent creating near-duplicate items from scratch. AI surfaces the closest existing items from Supplier Catalog, enabling merchants to reuse, modify, or replace rather than rebuild. Auto-population of line plan with potential items eliminates manual search and re-entry.',
    techIntegration: 'Primary OPIF: OPIF-337970 (Auto-populate Line Plan with Potential Items from Supplier Catalog through Item Repository/One Item workflow — Backlog). Related: OPIF-325203 (Shared Item Repository — Initial Requirements, Christopher Chiodo), OPIF-325568 (Move Fashion Line Planning to AP Tool — WIP). AI repository indexes Supplier Catalog and AEX item history. ML similarity scoring surfaces recommended items in AP Tool Assortment List and AEX line plan workflows. PRD: Shared Item Repository (Confluence APREC).',
    successMetrics: 'AI item reuse rate tracked and improving. New item creation time reduced for target merchant groups. Duplicate item rate decreasing quarter over quarter. Line plan auto-population from Supplier Catalog live for target departments.',
    owners: pptOwners('Brett Reid', 'Chris Graves', 'Ryan Henderson', 'Robbie Dutta', 'Mike Dunn'),
    resources: res(
      'https://jira.walmart.com/browse/OPIF-337970',
      '#',
      'https://confluence.walmart.com/pages/viewpage.action?pageId=3250398775',
      '#',
      [
        { label: 'OPIF-337970 — Auto-populate Line Plan from Supplier Catalog (Primary)', url: 'https://jira.walmart.com/browse/OPIF-337970' },
        { label: 'OPIF-325203 — Shared Item Repository (Related)', url: 'https://jira.walmart.com/browse/OPIF-325203' },
        { label: 'OPIF-325568 — Move Fashion LP to AP Tool (Related)', url: 'https://jira.walmart.com/browse/OPIF-325568' },
        { label: 'PRD: Shared Item Repository (Confluence APREC)', url: 'https://confluence.walmart.com/pages/viewpage.action?pageId=3250398775' },
        { label: 'LLTT Dashboard', url: 'https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard' },
      ]
    ),
    workstreams: ['buying'],
  },
  {
    id: 'size-pack-bq', title: 'Automated Size/Pack Buy Quantification', icon: '\uD83D\uDCE6',
    status: 'green', statusLabel: 'Green \u2014 Discovery Done',
    quarter: 'Q2', targetDate: 'Jul 31, 2026',
    description: 'Automation of size and pack buy quantification (BQ) calculations — eliminating the manual sizing step currently owned by merchants. Moves size logic into BQ module (calc changes in Flow Plan, removal of manual Size Profile screen in Size & Pack). Configurable minimum initial set qty for core sizes. Pre-generated DS results for all 3 Like Finelines recommended by AEX. Encompasses pack simplification for simpler execution. Requirements gathering underway. Jira: OPIF-325374.',
    businessBenefit: 'Removes the most time-consuming manual calculation in the buying process. Size curves derived from data rather than merchant memory, reducing size-related markdowns. Pack simplification reduces setup complexity in AEX BQ execution. Unified planner experience surfaces BQ and forecast outputs in one view without merchant reconciliation.',
    techIntegration: 'Primary OPIF: OPIF-325374 (Simplification of Pack for Simpler Execution — Requirements gathering). Related: OPIF-325218 (Buy Quantification and Flow as a Service — PRD: Confluence APREC), OPIF-325373 (Unified Planner Experience — PRD: Confluence APREC), OPIF-325221 (Forecast as a Service with Channel and Placement Split). Size/Pack BQ engine integrates with AEX demand signal, historical sell-through by size, and BPE for seasonal demand curve inputs. Discovery completed. PRD: Simplification of Pack (Confluence APREC).',
    successMetrics: 'Automated size/pack BQ in use across target departments by Jul 31. Manual sizing calculation time reduced to near zero. Size-based markdown rate decreasing. Unified planner experience adopted by all target buying teams.',
    owners: pptOwners('Brett Reid', 'Chris Graves', 'Abhishek Jannawar', 'Robbie Dutta', 'Mike Dunn'),
    resources: res(
      'https://jira.walmart.com/browse/OPIF-325374',
      '#',
      'https://confluence.walmart.com/display/APREC/Simplification+of+Pack',
      '#',
      [
        { label: 'OPIF-325374 — Simplification of Pack for Simpler Execution (Primary)', url: 'https://jira.walmart.com/browse/OPIF-325374' },
        { label: 'OPIF-325218 — Buy Quantification and Flow as a Service (Related)', url: 'https://jira.walmart.com/browse/OPIF-325218' },
        { label: 'OPIF-325373 — Unified Planner Experience (Related)', url: 'https://jira.walmart.com/browse/OPIF-325373' },
        { label: 'OPIF-325221 — Forecast as a Service with Channel & Placement Split (Related)', url: 'https://jira.walmart.com/browse/OPIF-325221' },
        { label: 'PRD: Simplification of Pack (Confluence APREC)', url: 'https://confluence.walmart.com/display/APREC/Simplification+of+Pack' },
        { label: 'PRD: BQ and Flow as a Service (Confluence APREC)', url: 'https://confluence.walmart.com/display/APREC/BQ+and+Flow+as+a+service' },
        { label: 'PRD: Unified Planner Experience (Confluence APREC)', url: 'https://confluence.walmart.com/display/APREC/Unified+Planner+Experience' },
        { label: 'LLTT Dashboard', url: 'https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard' },
      ]
    ),
    workstreams: ['buying', 'allocation'],
  },
  {
    id: 'ap-tool-lineplan', title: 'AP Tool Line Plan Integration w/ AEX', icon: '\uD83D\uDCC8',
    status: 'yellow', statusLabel: 'Yellow \u2014 Work in Progress',
    quarter: 'Q3', targetDate: 'July 31, 2026',
    jiraStatus: 'Work in Progress',
    priority: 'P3',
    techRank: 5,
    description: 'Integration of AP Tool (Assortment Planning) line plan with AEX, enabling assortment decisions from line planning to flow directly into buying execution without manual re-entry. Enables fashion merchants to use AP Plan Creation & Plan List as the Fashion Line Plan system of record (replaces AEX legacy LP module). Merchants get out of Excel permanently. Jira update (Mar 3, 2026): 03-Mar-2026 - Next Step: There is a 2 week spike stories and scope will be confirmed.  (ETA: 16-Mar). Timeline to be finalize post this spike ||Deliverables||Timeline || |Planned Start Date|17-Feb| |Development Complete| Path to Green: Working with Ashwin to get LOE.. Current status: Work in Progress. Assignee: Ashwin Chidambaram.',
    businessBenefit: 'Eliminates the gap between line planning (AP Tool) and buying execution (AEX). Merchants no longer re-enter line plan decisions into AEX manually. Fashion metrics are surfaced correctly in the new AP Assortment List environment. Excel upload capability reused eliminates re-keying of potential items.',
    techIntegration: 'Primary OPIF: OPIF-325568 (Move Fashion Line Planning to AP Tool Assortment List — Work in Progress, Q2 FY27). Related: OPIF-325216 (AEX Fashion: Use AP Plan Creation & Plan List — Initial Requirements), OPIF-325217 (Fashion Metrics Enablement in Assortment List & Downstream Validation), OPIF-325565 (Fashion Re-Use of AP Potential Item Excel Upload — Initial Requirements), OPIF-325569 (Streamline Merchant Supplier Comm Through Collab — related workflow). AP Tool line plan data syncs to AEX via shared integration layer. Fashion Excel Upload enabled via existing Assortment Planning capability. PRD: Transition Plan Creation and Line Planning to Assortment Planning (Confluence APREC).',
    successMetrics: 'AP Tool and AEX sharing live line plan data by Oct 30. Zero manual exports from AP Tool to AEX for in-scope workflows. Fashion metrics and attributes fully enabled in Assortment List. Supplier communication streamlined through Collab.',
    owners: pptOwners('Brett Reid', 'Ashwin Chidambaram', 'Taylor Watson', 'CJ Weatherford', 'Arun Santhiagu'),
    resources: res(
      'https://jira.walmart.com/browse/OPIF-325568',
      '#',
      'https://confluence.walmart.com/display/APREC/Transition+Plan+Creation+and+Line+Planning+to+Assortment+Planning',
      '#',
      [
        { label: 'OPIF-325568 — Move Fashion LP to AP Tool Assortment List (Primary — WIP)', url: 'https://jira.walmart.com/browse/OPIF-325568' },
        { label: 'OPIF-325216 — AEX Fashion: Use AP Plan Creation & Plan List (Related)', url: 'https://jira.walmart.com/browse/OPIF-325216' },
        { label: 'OPIF-325217 — Fashion Metrics Enablement in Assortment List (Related)', url: 'https://jira.walmart.com/browse/OPIF-325217' },
        { label: 'OPIF-325565 — Fashion Re-Use of AP Excel Upload (Related)', url: 'https://jira.walmart.com/browse/OPIF-325565' },
        { label: 'OPIF-325569 — Streamline Merchant Supplier Comm Through Collab (Related)', url: 'https://jira.walmart.com/browse/OPIF-325569' },
        { label: 'PRD: Transition Plan Creation & Line Planning to AP (Confluence APREC)', url: 'https://confluence.walmart.com/display/APREC/Transition+Plan+Creation+and+Line+Planning+to+Assortment+Planning' },
        { label: 'LLTT Dashboard', url: 'https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard' },
      ]
    ),
    workstreams: ['buying'],
  },
  {
    id: 'bam-collab-intent', title: 'BAM / Collab Intent Integration', icon: '\uD83E\uDD1D',
    status: 'green', statusLabel: 'Green \u2014 On Track',
    quarter: 'Q3', targetDate: 'Oct 30, 2026',
    description: 'Streamline merchant and supplier communication through Collab — integrating Collab as the single system of record for all supplier discussions within AEX, eliminating fragmented email communication. Requirements gathering underway. Jira: OPIF-325569 (Assignee: TBD).',
    businessBenefit: 'Buying decisions reflect collaborative intent data automatically — reducing the lag between collaboration signals and committed buy decisions. Eliminates email-based back-and-forth between merchants and suppliers. All supplier communication traceable and linked to specific assortment decisions.',
    techIntegration: 'Primary OPIF: OPIF-325569 (Streamline Merchant Supplier Communication Through Collab — Requirements gathering). Collab embedded into AEX as single system of record for supplier discussions. BAM and Collab Intent signals integrated into AEX via the shared event layer. Assortment recommendations weighted by collaborative intent scores. PRD: Streamline Merchant Supplier Communication through Collab (Confluence APREC).',
    successMetrics: 'BAM/Collab Intent data live in AEX buying workflow. Zero email-based supplier communication for in-scope workflows. Adoption confirmed across target buying teams by Oct 30. All supplier discussions linked to Jira OPIF or AEX assortment record.',
    owners: pptOwners('Brett Reid', 'Chris Graves', 'Ryan Henderson', 'Robbie Dutta', 'Mike Dunn'),
    resources: res(
      'https://jira.walmart.com/browse/OPIF-325569',
      '#',
      'https://confluence.walmart.com/display/APREC/Streamline+Merchant+Supplier+Communication+through+Collab',
      '#',
      [
        { label: 'OPIF-325569 — Streamline Merchant Supplier Comm Through Collab (Primary)', url: 'https://jira.walmart.com/browse/OPIF-325569' },
        { label: 'PRD: Streamline Merchant Supplier Communication (Confluence APREC)', url: 'https://confluence.walmart.com/display/APREC/Streamline+Merchant+Supplier+Communication+through+Collab' },
        { label: 'LLTT Dashboard', url: 'https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard' },
      ]
    ),
    workstreams: ['buying'],
  },
  {
    id: 'oneitem-expanded-sources', title: 'OneItem: Expanded Sources (ROM, 3P, Circana)', icon: '\uD83C\uDF10',
    status: 'green', statusLabel: 'Green \u2014 On Track',
    quarter: 'Q4', targetDate: 'Jan 30, 2027',
    description: 'Expansion of OneItem to include additional data sources: ROM (Range of Motion), 3rd-party data, and Circana — providing richer product intelligence for buying and assortment decisions.',
    businessBenefit: 'Merchants access a broader, richer set of market and performance signals in one place — improving buying decisions with external market context alongside internal data.',
    techIntegration: 'OneItem data pipeline expanded to ingest ROM, 3P market data feeds, and Circana retail data. Surfaced in AEX item records and assortment planning views.',
    successMetrics: 'ROM, 3P, and Circana sources live in OneItem. Merchant adoption of expanded data sources confirmed. Assortment decision quality (measured by sell-through) trending up.',
    owners: pptOwners('Brett Reid', 'Chris Graves', 'Abhishek Jannawar', 'Robbie Dutta', 'Mike Dunn'), resources: res(), workstreams: ['buying', 'strategy'],
  },
  {
    id: 'bq-enterprise-service', title: 'Buy Quantification as Enterprise Service', icon: '\uD83D\uDCCA',
    status: 'yellow', statusLabel: 'Yellow \u2014 Ready for Walkthrough',
    quarter: 'Q3', targetDate: 'Aug\u2013Oct 2026',
    description: 'Buy Quantification and Flow delivered as a shared enterprise service — providing demand-driven buy quantity recommendations across all Fashion workstreams without each team running independent BQ calculations. Part of the Recommend & Optimize phase of the LLTT roadmap (Q3 FY27 – Q1 FY28). Includes rollup reporting, dynamic PO re-distribution, pack simplification, unified planner experience, and channel/placement-split forecasting. OPIF-325218 Status: Discovery in Progress. Assignee: Abhishek Jannawar. Reporter: Abhishek Jannawar. Component: US Omni Tech – MerchTools – AEX Buy Quantification.',
    businessBenefit: 'Single authoritative buy quantity signal across all Fashion buying teams. Replaces manual BQ spreadsheets and per-department workarounds. Enables dynamic redistribution of POs as in-season signals emerge. Channel and placement splits give eComm and store teams differentiated signals.',
    techIntegration: 'Primary OPIF: OPIF-325218 (Buy Quantification and Flow as a Service — Requirements gathering). Related: OPIF-325221 (Forecast as a Service with Channel & Placement Split), OPIF-325373 (Unified Planner Experience), OPIF-325374 (Simplification of Pack for Simpler Execution). BQ enterprise service builds on DS National Forecasting microservice and automated size/pack work. Outputs consumed by AEX (commit), DBP (wave planning), and supply chain for automated PO creation. Includes rules-based Flow Plan automation. PRD: BQ and Flow as a Service (Confluence APREC).',
    successMetrics: 'BQ enterprise service adopted across all target Fashion buying departments. Manual BQ calculation workarounds eliminated. Dynamic PO re-distribution live and operational for in-season adjustments. Unified planner experience and channel-split forecasting adopted.',
    owners: pptOwners('Brett Reid', 'Chris Graves', 'Abhishek Jannawar', 'Robbie Dutta', 'Mike Dunn'),
    resources: res(
      'https://jira.walmart.com/browse/OPIF-325218',
      '#',
      'https://confluence.walmart.com/display/APREC/BQ+and+Flow+as+a+service',
      '#',
      [
        { label: 'OPIF-325218 — Buy Quantification and Flow as a Service (Primary)', url: 'https://jira.walmart.com/browse/OPIF-325218' },
        { label: 'OPIF-325221 — Forecast as a Service with Channel & Placement Split (Related)', url: 'https://jira.walmart.com/browse/OPIF-325221' },
        { label: 'OPIF-325373 — Unified Planner Experience (Related)', url: 'https://jira.walmart.com/browse/OPIF-325373' },
        { label: 'OPIF-325374 — Simplification of Pack for Simpler Execution (Related)', url: 'https://jira.walmart.com/browse/OPIF-325374' },
        { label: 'PRD: BQ and Flow as a Service (Confluence APREC)', url: 'https://confluence.walmart.com/display/APREC/BQ+and+Flow+as+a+service' },
        { label: 'PRD: Unified Planner Experience (Confluence APREC)', url: 'https://confluence.walmart.com/display/APREC/Unified+Planner+Experience' },
        { label: 'LLTT Dashboard', url: 'https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard' },
      ]
    ),
    workstreams: ['buying', 'allocation'],
  },
  {
    id: 'commitment-report-redesign', title: 'Commitment Report Redesign', icon: '\uD83D\uDCDD',
    status: 'green', statusLabel: 'Green \u2014 In Progress',
    quarter: 'Q2', targetDate: 'Jul 31, 2026',
    description: 'Full redesign of the Commitment Report (CR) module in AEX — including COMBO CR across all suppliers, improved Excel export with TY item descriptions and offshore store highlighting, store summary graph improvements, and a Pre-Commit screen with unit presentation at fineline/color level. Enables download of multiple CR exports at once and UI to access previously generated reports.',
    businessBenefit: 'Reduces time buyers spend compiling and reformatting commitment reports for vendor communication. Combo CR eliminates the need to generate and merge multiple single-supplier reports.',
    techIntegration: 'Tracked across multiple OPIF/MTAP tickets. Key items: MTAP-9638 (CR multi-export, Backlog), MTAP-9879 (Pre-commit screen, Backlog). AEX CR module, store distribution data, and vendor communication workflows.',
    successMetrics: 'COMBO CR adopted as standard across all Fashion buying teams. Pre-commit screen live and reducing vendor miscommunication incidents. CR generation time reduced measurably.',
    owners: pptOwners('Brett Reid', 'Chris Graves', 'Amy Caley', 'Robbie Dutta', 'Mike Dunn'),
    resources: res('https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard'),
    workstreams: ['buying'],
  },
  {
    id: 'shared-item-repository', title: 'Shared Item Repository (OneItem)', icon: '\uD83D\uDDC4\uFE0F',
    status: 'roadmap', statusLabel: 'Roadmap \u2014 Recommend & Optimize Phase',
    quarter: 'Q3', targetDate: 'Aug\u2013Oct 2026',
    description: 'Unified item repository serving as the single source of truth for Fashion product items across the E2E workflow — connecting AEX, Line Planning, Supplier Catalog, and item creation systems. Requirements gathering underway. Jira: OPIF-325203 (Christopher Chiodo, Initial Requirements). Enables auto-population of line plan with potential items from Supplier Catalog through OneItem. Expanded sources include ROM, 3P data, and Circana retail signals.',
    businessBenefit: 'Eliminates duplicate item creation and conflicting item data across systems. Merchants select from a shared, AI-curated item repository rather than building items from scratch each season. Single item record shared across AEX, Centric, and Supplier One eliminates re-entry.',
    techIntegration: 'Primary OPIF: OPIF-325203 (Shared Item Repository — Initial Requirements, Christopher Chiodo). Related: OPIF-337970 (Auto-populate Line Plan with Potential Items from Supplier Catalog — Backlog), OPIF-325188 (Shared Project Tracking and Event Calendar — Initial Requirements), OPIF-325568 (Move Fashion LP to AP Tool — WIP). Integrates with AEX Assortment List, Supplier One catalog, OneItem workflow, and ISAM for item setup. Auto-populates LP with potential items. Circana, ROM, and 3P data feeds expand intelligence. PRD: Shared Item Repository (Confluence APREC).',
    successMetrics: 'Shared Item Repository live and auto-populating line plans for target departments. Duplicate item creation rate eliminated. Item repository sourcing all ROM, 3P, and Circana signals confirmed.',
    owners: pptOwners('Brett Reid', 'Chris Graves', 'David Nelms', 'Robbie Dutta', 'Mike Dunn'),
    resources: res(
      'https://jira.walmart.com/browse/OPIF-325203',
      '#',
      'https://confluence.walmart.com/pages/viewpage.action?pageId=3250398775',
      '#',
      [
        { label: 'OPIF-325203 — Shared Item Repository (Primary)', url: 'https://jira.walmart.com/browse/OPIF-325203' },
        { label: 'OPIF-337970 — Auto-populate Line Plan from Supplier Catalog (Related)', url: 'https://jira.walmart.com/browse/OPIF-337970' },
        { label: 'OPIF-325188 — Shared Project Tracking and Event Calendar (Related)', url: 'https://jira.walmart.com/browse/OPIF-325188' },
        { label: 'OPIF-325568 — Move Fashion LP to AP Tool (Related)', url: 'https://jira.walmart.com/browse/OPIF-325568' },
        { label: 'PRD: Shared Item Repository (Confluence APREC)', url: 'https://confluence.walmart.com/pages/viewpage.action?pageId=3250398775' },
        { label: 'LLTT Dashboard', url: 'https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard' },
      ]
    ),
    workstreams: ['buying', 'design'],
  },
  {
    id: 'global-buying-platform', title: 'Global Buying Capability', icon: '\uD83C\uDF0D',
    status: 'roadmap', statusLabel: 'Roadmap',
    quarter: 'Q4', targetDate: 'Nov 2026\u2013Jan 2027',
    description: 'Extension of the Fashion buying platform to support global segment needs — multi-currency, multi-market assortment planning and buy execution within AEX.',
    businessBenefit: 'International Fashion teams leverage the same buying workflow as domestic teams — eliminating global-specific tooling debt and enabling cross-market visibility.',
    techIntegration: 'AEX global capability requires multi-currency support, market-specific assortment logic, and integration with international supplier and item setup systems.',
    successMetrics: 'At least one global market piloted in AEX by end of Q4. Roadmap for remaining global markets defined and funded.',
    owners: TBD_OWNERS(), resources: res(), workstreams: ['buying'],
  },
];