// data-goals.js — LLTT Transformation Goal details
// Source: APREC Confluence — LLTT Work Management Dashboard (read Mar 2026)
// https://confluence.walmart.com/display/APREC/Long+Lead+Time+Transformation+Work+Management+Dashboard

const GOALS = {
  '1': {
    id: '1',
    label: '90% of Buys on Happy Path',
    icon: '\uD83D\uDEF3\uFE0F',
    target: '90% of fashion apparel buys complete the full AEX workflow end-to-end without exceptions, manual workarounds, or out-of-tool steps — AND execution steps (bridge → item creation → PO creation) complete successfully without manual engineering intervention.',
    baseline: 'Significantly below 90% today. Gap is evidenced by siloed modules, manual reallocations, broken event tracking, frequent tool exits, AND known execution failure modes: finelines stuck in \'Initiation Successful\' state, CR-to-ADS bridge failures, 9-digit supplier ID issues, item attribute mismatches breaking PO creation.',
    status: 'in-progress',
    phases: [1],
    workstreams: ['Line Planning', 'Assortment Product', 'Buy Quantification', 'Commitment Report', 'Execution', 'Size & Pack Optimization', 'System Enhancements', 'eComm End-to-End'],
    description: 'A \'happy path buy\' is one that flows end-to-end through AEX sequentially without any human workaround, system exit, or manual step — AND completes execution successfully without failures or engineering intervention. This combines two complementary measures: (1) Process Flow Adherence: buys follow the 12-step in-tool journey (CSA Space Upload → Line Plan → ... → Pack Optimization → Item/PO Creation) without exits, and (2) Execution Success: bridge, item creation, and PO creation steps complete without getting stuck or failing. Previously tracked as separate goals (#1 Happy Path Flow + #3 Happy Path Execution), now unified as a single comprehensive goal.',
    keyPrograms: [
      'AP Tool Integration — Replace Line Plan in AEX with the Assortment Planning Tool',
      'Item Selection (Repository Connection) — Auto-populate items from OneSource/MINT',
      'Automated BQ — Eliminate manual Size & Pack steps',
      'New Store PO Automation — Remove manual PO creation',
      'Lock All Modules After a FL is Bridged — Prevent state drift across modules',
      'Display Item and PO Status to Users + Ability to Re-Bridge Finelines — Self-service recovery',
      'Alert and Block Users from Downloading Commit Reports Lacking Pre-Reqs — Prevent downstream failures',
      'Lock Pack Optimization After CR is Bridged — Ensure data integrity post-commit',
      'Exception Reporting — Surface stuck/failed finelines proactively',
      'Backend Work to Support Re-Bridge FLs and Display Quote, Item, and PO Status',
    ],
  },
  '2': {
    id: '2',
    label: 'Zero Rekeys Across E2E Workflow',
    icon: '\u2327',
    target: '0 manual rekey touchpoints across the entire E2E fashion workflow — Line Plan through Item Creation through PO Creation.',
    baseline: 'Multiple documented rekey points today: (1) Users download AEX extract → upload into AIMS for FC POs, (2) Merchants re-enter Size & Pack inputs manually, (3) Supplier item details entered separately in email AND the planning tool, (4) Commitment Report data not flowing systematically to markdown/replenishment systems.',
    status: 'in-progress',
    phases: [1],
    workstreams: ['Line Planning', 'Commitment Report', 'Execution', 'eComm End-to-End', 'System Enhancements'],
    description: 'Rekeys are any instances where data must be manually re-entered into a different system because the prior system does not feed it automatically. The AEX Problem Overview explicitly documents this as a core pain point. Zero Rekeys means 100% of data flows systematically from one step to the next — no manual copy/paste, no spreadsheet intermediaries, no email round-trips.',
    keyPrograms: [
      'Supplier One Integration — Direct integration replacing email-based supplier communication',
      'Online Item PO Creation — Systematically create eComm POs from AEX (eliminating AIMS manual upload)',
      'Item 360 Integration — Commitment Report changes to capture item validation automatically',
      'Streamline Merchant-Supplier Communication via Collab — OneSource/Collab integration for BAM',
      'Intended Item Report Standardization — Standardize data flow for item proposals',
      'Systematic Data Ingestion to Markdown & Replenishment Systems',
    ],
  },
  '2': {
    id: '4',
    label: 'Reduce Merchant Hours',
    icon: '\u23F1\uFE0F',
    target: 'Directional reduction in total time merchants spend on low-value, manual, repetitive planning tasks. Phase 3 shifts the merchant role from manual planner to strategy encoder.',
    baseline: 'Significant unquantified manual burden: multiple tool toggles, manual Size & Pack runs, no in-tool analytics, Excel-based planning, season-by-season manual rebuilds.',
    status: 'in-progress',
    phases: [1, 3],
    workstreams: ['Line Planning', 'Buy Quantification', 'Assortment Product', 'Financial Review', 'Usability', 'Admin Screens'],
    description: 'Reducing the total time merchants spend on low-value, repetitive, manual planning tasks. Phase 1 reduces hours by systemizing workflows and removing tool exits. Phase 3 (Automate) further reduces hours by enabling strategy encoding and scenario generation — merchants set strategic parameters rather than building plans manually. The LP Redesign initiative specifically calls out \'Get Merchants Out of Excel\' as the core baseline problem.',
    keyPrograms: [
      'LP Redesign — Get Merchants Out of Excel; add Style # flow, multi-select size group, historical data',
      'BQ Redesign (BuyPlanSimplification) — Pre-generate DS results, configurable min initial set qty',
      'Automated Flow Plan (Rules-Based Engine) — Automate flow strategy decisions',
      'On-Demand Store Volume Groups & Size Curves — Reduce analytics input time',
      'Assortment Optimization Engine — Reduce manual assortment decision work',
      'Strategy Repo/Capture (Phase 3) — Merchants encode strategy once; system builds plans',
      'Scenario Generation and Selection (Phase 3)',
    ],
  },
  '5': {
    id: '5',
    label: 'Reduce Trapped Inventory',
    icon: '\uD83D\uDCE6',
    target: 'Directional reduction in fashion inventory that ends up in the wrong location after commit — enabled by in-season redistribution and dynamic placement capabilities.',
    baseline: 'Effectively 0% systematic redistribution capability today. 100% of the buy is locked at commit time with no in-tool recovery mechanism. All redistribution is manual, ad hoc, and rare.',
    status: 'planned',
    phases: [2, 3],
    workstreams: ['Buy Quantification', 'Execution', 'eComm End-to-End', 'Mod Execution', 'Chase Buys', 'System Enhancements'],
    description: 'Trapped inventory is fashion product ordered (committed via PO) that ends up in the wrong location — wrong store, wrong DC, wrong channel — making it unable to sell at full price. It becomes trapped because the long lead time of fashion (9–12+ months) means errors in buy planning have no recovery under the current workflow. LLTT unlocks in-season redistribution and dynamic placement to free this inventory.',
    keyPrograms: [
      'Dynamic PO Re-Distribution — Systematically redirect committed POs to better-fit stores',
      'Tag-based In-Season Swaps — Use fixture/style tags to recommend product swaps between stores',
      'Forecast as Enterprise Service — Better upfront forecasting reduces initial placement errors',
      'Buy Quantification as Enterprise Service — Shared BQ reduces siloed buy errors',
      'Tag-based In-Season Dynamic Placement (Phase 3) — Fully automate placement decisions in-season',
      'Chase Buys — Plan and execute mid-season buys for in-demand items',
    ],
  },
  '6': {
    id: '6',
    label: '85% Shop In-Stock Rate',
    icon: '\uD83D\uDED2',
    target: '85% of shopping trips result in the customer finding the fashion item they are looking for in stock, in their size and color.',
    baseline: 'Below 85% today. Contributing causes: poor forecasting (no national forecast in line planning), manual BQ leading to inaccurate quantities, no replenishment automation linked to BQ flag, and wrong product in wrong stores.',
    status: 'planned',
    phases: [2, 3],
    workstreams: ['Buy Quantification', 'Line Planning', 'Execution', 'Mod Execution', 'eComm End-to-End', 'System Enhancements'],
    description: 'The shop in-stock rate measures the percentage of time a customer visiting a fashion department finds the items they are looking for in stock (by size, color, style). An 85% target means that 85% of shopping trips result in a successful purchase. Directly tied to top-line sales, customer satisfaction, and reduced markdown/clearance pressure.',
    keyPrograms: [
      'Forecast as Enterprise Service — National forecast visibility replacing manual fineline-level estimates',
      'Buy Quantification as Enterprise Service — More accurate quantity planning per store cluster',
      'National Forecast Visibility in Line Planning — Feed DS forecast into LP before BQ',
      'DS Buy Quantification (V1 & V2) — Data science-driven buy quantities',
      'Add Replenishment UPCs to Label Mods When Executed — Use BQ replenishment flag for modular execution',
      'DS Store Segmentation / Store Volume Groups / Size Curves — Store-level accuracy',
      'Tag-based In-Season Dynamic Placement (Phase 3)',
    ],
  },
  '7': {
    id: '7',
    label: '90% PO Redistribution Coverage',
    icon: '\uD83D\uDD04',
    target: '90% of eligible Purchase Orders are covered by the dynamic PO redistribution capability — either automated or system-recommended.',
    baseline: 'Effectively 0% systematic coverage today. Redistribution is fully manual, ad hoc, and rare. No in-tool capability exists in the current AEX workflow.',
    status: 'planned',
    phases: [2],
    workstreams: ['Execution', 'Buy Quantification', 'System Enhancements', 'eComm End-to-End'],
    description: 'PO redistribution is the ability to dynamically redirect committed Purchase Orders — after the original buy is placed — to different stores, DCs, or channels based on in-season demand signals. Today this is a fully manual, exception-based process. 90% coverage means the system can recommend or execute redistribution for 90% of applicable POs.',
    keyPrograms: [
      'Dynamic PO Re-Distribution — Core Phase 2 deliverable; the primary technical vehicle',
      'Tag-based In-Season Swaps — Prerequisite: tagging/fixture library enables store matching',
      'Shared Event Calendar & Actions — Coordination layer for redistribution decisions',
      'Forecast as Enterprise Service — In-season demand signals trigger redistribution',
      'Buy Quantification as Enterprise Service — Shared BQ enables redistribution calculations',
    ],
  },
  '8': {
    id: '8',
    label: 'Increase Sell-Through Rate',
    icon: '\uD83D\uDCC8',
    target: 'Directional increase in the percentage of ordered inventory that sells at full or near-full price before markdown/clearance. Named initiative: Fresh Waste (Markdown/Loss) Reduction.',
    baseline: 'Fashion apparel struggles with sell-through due to long lead times creating demand forecast uncertainty. Significant markdown/clearance activity currently eating into margins.',
    status: 'planned',
    phases: [2, 3],
    workstreams: ['Buy Quantification', 'Line Planning', 'Execution', 'Mod Execution', 'eComm End-to-End', 'Chase Buys', 'System Enhancements'],
    description: 'Sell-through rate is the percentage of ordered inventory that sells at full or near-full price before markdown/clearance. Higher sell-through means less dead inventory, fewer markdowns, better margin, and reduced clearance costs. This is the ultimate financial outcome metric for LLTT — if Goals #5 (trapped inventory), #6 (in-stock), and #7 (PO redistribution) all improve, sell-through increases as a result.',
    keyPrograms: [
      'Fresh Waste (Markdown/Loss) Reduction — Named initiative directly targeting sell-through',
      'Tag-based In-Season Dynamic Placement (Phase 3) — Right product, right store, right time',
      'Chase Buys — Replenish winning items mid-season, reducing OOS drag on sell-through',
      'Assortment Optimization Engine — Better initial assortment selection = higher sell-through',
      'DS Forecasting with Model Explainability — Accurate demand forecasting reduces over/under buying',
      'Systematic Data Ingestion to Markdown & Replenishment Systems — Close feedback loop',
    ],
  },
};